In [86]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [87]:
df = pd.read_csv('stocks_quarterly.csv')

In [88]:
df.head(30)

,fiscalDateEnding,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,investmentIncomeNet,...,surprisePercentage,price,nasd_price,next_year_date,next_year_price,nasd_ny_price,symbol,Nasdaq_Performance,Stock_Performance,Label
0,2020-12-31,4.027000e+09,4.027000e+09,4.485000e+09,1.240000e+09,-2.515000e+09,1.860000e+08,NaN,1.127000e+09,5000000.0,...,6.3380,18.100000,13337.160156,2022-01-28,15.640000,13770.570313,AAL,3.249643,-13.591160,0
1,2020-09-30,-2.310000e+09,2.833000e+09,5.143000e+09,1.156000e+09,-2.871000e+09,7.000000e+07,NaN,1.941000e+09,5000000.0,...,3.7309,13.150000,11506.009766,2021-10-22,19.150000,15090.200195,AAL,31.150594,45.627378,1
2,2020-06-30,-2.601000e+09,1.368000e+09,3.969000e+09,8.660000e+08,-2.486000e+09,4.300000e+07,NaN,1.133000e+09,10000000.0,...,0.9575,11.770000,10461.419922,2021-07-23,21.200001,14836.990234,AAL,41.825778,80.118946,1
3,2020-03-31,1.241000e+09,8.258000e+09,7.017000e+09,2.197000e+09,-2.549000e+09,3.050000e+08,NaN,2.857000e+09,21000000.0,...,-12.5218,12.010000,8889.549805,2021-04-30,21.719999,13962.679688,AAL,57.068468,80.849283,1
4,2019-12-31,1.118900e+10,1.131300e+10,1.240000e+08,2.633000e+09,7.290000e+08,5.030000e+08,NaN,1.240000e+08,24000000.0,...,-0.5104,28.799999,9402.480469,2021-01-22,15.820000,13543.059570,AAL,44.037093,-45.069444,0
5,2019-09-30,4.329000e+09,1.162700e+10,7.298000e+09,2.854000e+09,8.080000e+08,4.240000e+08,NaN,2.508000e+09,34000000.0,...,1.6100,29.410000,8185.799805,2020-10-23,12.600000,11548.280273,AAL,41.076994,-57.157428,0
6,2019-06-30,4.615000e+09,1.168500e+10,7.070000e+09,2.864000e+09,1.153000e+09,4.010000e+08,NaN,2.277000e+09,35000000.0,...,1.7726,31.670000,8238.540039,2020-07-24,11.390000,10363.179688,AAL,25.789031,-64.035364,0
7,2018-12-31,1.071100e+10,1.093800e+10,2.270000e+08,2.748000e+09,5.710000e+08,4.720000e+08,NaN,2.270000e+08,34000000.0,...,3.4106,33.660000,7073.459961,2020-01-24,27.639999,9314.910156,AAL,31.688173,-17.884731,0
8,2018-09-30,4.077000e+09,1.129400e+10,7.217000e+09,3.043000e+09,6.850000e+08,3.950000e+08,NaN,2.341000e+09,29000000.0,...,0.4177,32.369999,7318.339844,2019-10-25,30.860001,8243.120117,AAL,12.636476,-4.664808,0
9,2018-06-30,4.369000e+09,1.137700e+10,7.008000e+09,2.898000e+09,1.004000e+09,3.478000e+09,NaN,5.441000e+09,30000000.0,...,2.4706,40.020000,7852.180176,2019-07-26,31.240000,8330.209961,AAL,6.087861,-21.939032,0
10,2018-03-31,3.648000e+09,1.013600e+10,6.488000e+09,2.529000e+09,3.960000e+08,3.373000e+09,NaN,5.220000e+09,25000000.0,...,5.6041,42.369999,7118.680176,2019-04-26,33.060001,8146.399902,AAL,14.436942,-21.973089,0
11,2017-12-31,1.046100e+10,1.060000e+10,1.390000e+08,2.395000e+09,6.380000e+08,6.175000e+09,NaN,1.390000e+08,24000000.0,...,3.2833,53.049999,7411.160156,2019-01-25,34.980000,7164.859863,AAL,-3.323370,-34.062205,0
12,2017-09-30,4.315000e+09,1.061200e+10,6.297000e+09,2.345000e+09,1.256000e+09,3.395000e+09,NaN,5.172000e+09,25000000.0,...,1.5737,48.610001,6556.770020,2018-10-26,32.459999,7167.209961,AAL,9.310071,-33.223619,0
13,2017-03-31,3.556000e+09,9.367000e+09,5.811000e+09,2.137000e+09,7.370000e+08,3.143000e+09,NaN,4.828000e+09,21000000.0,...,6.5688,43.980000,6048.939941,2018-04-27,43.400002,7119.799805,AAL,17.703265,-1.318777,0
14,2020-09-30,-1.216900e+07,4.626900e+07,5.843800e+07,NaN,-1.522100e+07,1.160000e+05,NaN,1.160000e+05,NaN,...,NaN,2.060000,12888.280273,2021-12-31,2.450000,15644.969727,AAME,21.389118,18.932044,0
15,2020-06-30,-4.415000e+06,4.973700e+07,5.415200e+07,NaN,-7.527000e+06,4.080000e+05,NaN,4.080000e+05,NaN,...,NaN,2.000000,11167.509766,2021-09-30,4.150000,14448.580078,AAME,29.380501,107.500005,1
16,2020-03-31,-2.792200e+07,3.941000e+07,6.733200e+07,NaN,-3.122700e+07,3.530000e+05,NaN,3.530000e+05,NaN,...,NaN,1.660000,10058.769531,2021-06-30,4.320000,14503.950195,AAME,44.192092,160.240979,1
17,2019-12-31,-5.366300e+07,5.228900e+07,1.059520e+08,6.713900e+07,6.578700e+07,4.150000e+05,NaN,7.883100e+07,NaN,...,NaN,2.110000,7700.100098,2021-03-31,3.680000,13246.870117,AAME,72.035038,74.407595,1
18,2019-09-30,-2.169300e+07,4.774500e+07,6.943800e+07,3.941500e+07,-2.445900e+07,3.380000e+05,NaN,3.380000e+05,NaN,...,NaN,1.970000,8972.599609,2020-12-30,2.100000,12870.000000,AAME,43.436691,6.598978,0
19,2019-06-30,-2.517500e+07,4.312700e+07,6.830200e+07,3.863100e+07,-2.768600e+07,5.560000e+05,NaN,5.560000e+05,NaN,...,NaN,2.770000,7999.339844,2020-09-29,1.980000,11085.250000,AAME,38.577060,-28.519854,0
20,2018-09-30,-1.980400e+07,4.637000e+07,6.617400e+07,3.541800e+07,-2.276400e+07,7.000000e+04,NaN,7.000000e+04,NaN,...,NaN,2.410000,6635.279785,2019-12-31,1.970000,8972.599609,AAME,35.225641,-18.257263,0
21,2020-12-31,1.127700e+07,5.232600e+07,5.466100e+07,4.104900e+07,-1.316100e+07,1.361200e+07,10826000.0,2.443800e+07,35000.0,...,13.7559,11.170000,13119.429688,2022-02-25,3.450000,13694.620117,AAOI,4.384264,-69.113697,0
22,2020-09-30,1.919000e+07,7.485700e+07,7.228100e+07,5.741800e+07,-6.779000e+06,1.476300e+07,11206000.0,2.596900e+07,26000.0,...,29.0780,10.020000,11890.929688,2021-11-05,5.860000,15971.589844,AAOI,34.317419,-41.516967,0
23,2020-06-30,1.373600e+07,6.384600e+07,6.562700e+07,5.148600e+07,-1.110800e+07,1.404100e+07,10803000.0,2.484400e+07,47000.0,...,5.1008,15.050000,11108.070313,2021-08-06,7.150000,14835.759766,AAOI,33.558389,-52.491694,0
24,2020-03-31,6.338000e+06,3.915100e+07,5.373400e+07,3.412900e+07,-1.779400e+07,1.357400e+07,10558000.0,2.413200e+07,147000.0,...,-18.1525,12.200000,8979.660156,2021-05-07,7.580000,13752.240234,AAOI,53.148783,-37.868852,0
25,2019-12-31,1.133600e+07,4.865800e+07,5.011500e+07,3.732200e+07,-1.205400e+07,1.279300e+07,10597000.0,2.339000e+07,196000.0,...,21.6369,9.560000,8566.480469,2021-02-26,9.325000,13192.349609,AAOI,53.999646,-2.458165,0
26,2019-09-30,1.197600e+07,4.488900e+07,4.671400e+07,3.410800e+07,-1.099600e+07,1.250600e+07,10466000.0,2.297200e+07,347000.0,...,37.1596,11.710000,8410.629883,2020-11-05,10.020000,11890.929688,AAOI,41.379776,-14.432106,0
27,2019-06-30,1.053800e+07,4.213700e+07,4.618800e+07,3.287300e+07,-1.382800e+07,1.321500e+07,11151000.0,2.436600e+07,310000.0,...,30.5556,10.210000,7862.830078,2020-08-06,15.050000,11108.070313,AAOI,41.273183,47.404507,1
28,2019-03-31,1.235100e+07,5.148100e+07,5.935100e+07,4.036800e+07,-1.186900e+07,1.303500e+07,11185000.0,2.422000e+07,72000.0,...,-24.5962,12.060000,7943.319824,2020-05-07,12.200000,8979.660156,AAOI,13.046690,1.160857,0
29,2018-12-31,1.053700e+07,5.801800e+07,5.895300e+07,4.748100e+07,-1.227700e+07,1.147200e+07,11342000.0,2.281400e+07,59000.0,...,54.3379,14.600000,7459.709961,2020-02-21,11.280000,9576.589844,AAOI,28.377509,-22.739730,0

### Drop columns with more tha 15% of nan's

In [71]:
cols_to_drop = df.isnull().mean().sort_values(ascending = False).head(45).index

In [72]:
df.drop(columns = cols_to_drop, inplace = True)

In [73]:
df = df.drop(columns = ['fiscalDateEnding','reportedDate','price','nasd_price','next_year_date','next_year_price','nasd_ny_price','symbol','Nasdaq_Performance', 'Stock_Performance'])

### Class balance

In [89]:
df.Label.value_counts()

0    3572
1    1815
Name: Label, dtype: int64

### DF info

In [90]:
df.describe()

,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,researchAndDevelopment,operatingExpenses,investmentIncomeNet,netInterestIncome,...,estimatedEPS,surprise,surprisePercentage,price,nasd_price,next_year_price,nasd_ny_price,Nasdaq_Performance,Stock_Performance,Label
count,5.289000e+03,5.189000e+03,5.272000e+03,4.780000e+03,5.329000e+03,5.335000e+03,2.681000e+03,5.352000e+03,1.545000e+03,4.492000e+03,...,4873.000000,4873.000000,4709.000000,5387.000000,5387.000000,5387.000000,5387.000000,5387.000000,5387.000000,5387.000000
mean,9.905868e+09,1.375088e+10,1.056922e+13,1.165695e+13,1.641398e+09,5.110055e+09,1.339470e+08,5.123648e+09,2.277770e+07,5.789404e+09,...,-0.638648,0.048021,-4.510933,48.139493,8443.263409,51.207522,10669.864834,25.632222,21.873372,0.336922
std,2.726647e+11,2.097089e+11,7.673180e+14,8.058405e+14,3.958536e+10,8.639635e+10,7.980184e+08,1.648603e+11,1.287905e+08,1.271873e+11,...,33.896404,8.967016,886.234479,124.946996,1906.328372,127.910618,2998.139271,18.054990,109.421843,0.472702
min,-6.043858e+12,-2.037500e+10,-2.550465e+09,-6.574000e+09,-2.326840e+11,-1.933600e+10,-2.590900e+07,-2.751511e+12,-5.500000e+07,-2.449781e+09,...,-1720.000000,-413.333300,-24700.000000,0.200000,5552.939941,0.222000,6332.990234,-12.239378,-98.676056,0.000000
25%,1.565262e+06,1.547600e+07,7.997750e+06,7.117250e+06,-6.455000e+06,4.179000e+06,1.068000e+06,8.892750e+06,3.411700e+04,-1.560000e+07,...,-0.110000,-0.029700,-7.777800,7.840000,7200.870117,7.142864,7891.779785,10.434127,-22.159395,0.000000
50%,4.168200e+07,1.325950e+08,6.501900e+07,6.740900e+07,4.035305e+06,2.207000e+07,6.800000e+06,4.400000e+07,4.540000e+05,-1.709780e+06,...,0.235700,0.021900,4.852000,23.520000,7891.779785,23.700001,9572.150391,23.826696,4.677269,0.000000
75%,2.976270e+08,8.864000e+08,4.251355e+08,4.154895e+08,7.114300e+07,1.110000e+08,2.666200e+07,2.178232e+08,3.000000e+06,-1.500000e+04,...,0.647500,0.091700,21.739100,52.250000,9192.339844,56.155001,13632.839844,38.577060,36.505750,1.000000
max,1.040561e+13,4.059117e+12,5.571384e+16,5.571384e+16,1.252340e+12,1.743446e+12,1.924500e+10,7.260568e+12,1.505000e+09,3.101895e+12,...,44.430200,380.000000,44566.666700,2920.000000,14047.500000,2618.969971,16057.440430,95.110363,2914.070410,1.000000

In [91]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5387 entries, 0 to 5386
Columns: 102 entries, fiscalDateEnding to Label
dtypes: float64(97), int64(1), object(4)
memory usage: 4.2+ MB

### Baseline Model

In [77]:
df = df.fillna()

In [58]:
X = df.drop(columns = 'Label')
y = df.Label

In [80]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate

model = LogisticRegression(solver='liblinear')

cv = cross_validate(model,X,y, scoring = 'accuracy')

/Users/patriciogarbino/.pyenv/versions/3.8.12/envs/lewagon/lib/python3.8/site-packages/sklearn/svm/_base.py:946: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  coef = sp.vstack(coef).tocsr()

In [85]:
cv['test_score'].mean()

0.5513363410697274

In [83]:
1815/5387

0.33692222015964357

In [81]:
df

,grossProfit,totalRevenue,costOfRevenue,costofGoodsAndServicesSold,operatingIncome,sellingGeneralAndAdministrative,operatingExpenses,interestExpense,depreciationAndAmortization,incomeBeforeTax,...,cashflowFromInvestment,cashflowFromFinancing,proceedsFromRepurchaseOfEquity,changeInCashAndCashEquivalents,netIncome_y,reportedEPS,estimatedEPS,surprise,surprisePercentage,Label
0,4.027000e+09,4.027000e+09,4.485000e+09,1.240000e+09,-2.515000e+09,186000000.0,1.127000e+09,376000000.0,483000000.0,-2.841000e+09,...,1.696000e+09,1.269000e+09,1.443000e+09,-2.515000e+09,-2.178000e+09,-3.8600,-4.1212,0.2612,6.3380,0
1,-2.310000e+09,2.833000e+09,5.143000e+09,1.156000e+09,-2.871000e+09,70000000.0,1.941000e+09,340000000.0,498000000.0,-3.095000e+09,...,9.230000e+08,1.511000e+09,0.000000e+00,-2.399000e+09,-2.399000e+09,-5.5400,-5.7547,0.2147,3.7309,1
2,-2.601000e+09,1.368000e+09,3.969000e+09,8.660000e+08,-2.486000e+09,43000000.0,1.133000e+09,254000000.0,499000000.0,-2.659000e+09,...,-6.799000e+09,7.688000e+09,1.525000e+09,-2.067000e+09,-2.067000e+09,-7.8200,-7.8956,0.0756,0.9575,1
3,1.241000e+09,8.258000e+09,7.017000e+09,2.197000e+09,-2.549000e+09,305000000.0,2.857000e+09,257000000.0,560000000.0,-2.890000e+09,...,-1.620000e+08,5.260000e+08,-1.710000e+08,1.960000e+08,-2.241000e+09,-2.6500,-2.3551,-0.2949,-12.5218,1
4,1.118900e+10,1.131300e+10,1.240000e+08,2.633000e+09,7.290000e+08,503000000.0,1.240000e+08,265000000.0,513000000.0,5.710000e+08,...,6.390000e+08,-1.272000e+09,-2.720000e+08,7.710000e+08,4.140000e+08,1.1500,1.1559,-0.0059,-0.5104,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5382,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.490550e+05,149055.0,1.490550e+05,535200.0,0.0,3.861400e+05,...,-1.148800e+06,7.800000e+05,0.000000e+00,-4.659760e+05,3.861400e+05,-0.0834,0.0000,0.0000,0.0000,0
5383,-4.841080e+05,0.000000e+00,4.841080e+05,4.841080e+05,-1.124270e+05,112427.0,1.124270e+05,573980.0,0.0,4.615500e+05,...,-1.148800e+06,5.008000e+05,0.000000e+00,-7.599410e+05,5.394090e+05,-0.0181,0.0000,0.0000,0.0000,0
5384,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-8.079500e+04,80795.0,8.079500e+04,617380.0,0.0,5.365800e+05,...,-1.148800e+06,1.148800e+06,0.000000e+00,5.365840e+05,5.365840e+05,0.0111,0.0000,0.0000,0.0000,0
5385,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.371450e+05,137145.0,1.371450e+05,1383110.0,0.0,1.092230e+06,...,-1.148800e+06,1.148800e+06,0.000000e+00,5.572150e+05,5.572150e+05,-0.0078,0.0000,0.0000,0.0000,0
5386,0.000000e+00,0.000000e+00,-3.716810e+05,-3.716810e+05,-2.181400e+04,21814.0,2.181400e+04,0.0,0.0,-1.628811e+06,...,-1.378559e+08,-1.148800e+06,1.173200e+06,-2.181400e+04,-2.181400e+04,0.0147,0.0000,0.0147,0.0000,0